version: '3.8'

services:
  # Serveur SFTP sécurisé pour simuler le dépôt des logs de l'application
  sftp_server:
    image: atmoz/sftp
    volumes:
      - ./data/temp_sftp:/home/${SFTP_USER}/upload
    ports:
      - "2222:22"
    # L'image Atmoz prend le format utilisateur:mot_de_passe:uid
    command: ${SFTP_USER}:${SFTP_PASSWORD}:1001

  # Entrepôt de données décisionnel (Data Warehouse) basé sur PostgreSQL
  postgres_dwh:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: